theme: jekyll-theme-minimal
title: Melinda Higgins, PhD
description: [Director of Biostatistics and Data Core - ONR](https://www.nursing.emory.edu/office-of-nursing-research); Research Professor; [Melinda's website](https://melindahiggins.netlify.app/)
# logo: https://assets-global.website-files.com/5f11b12012400490893a64ea/5f11b1201240041bcb3a6700_higgin.jpg
